{{- if .Values.websocket.cluster_issuer_enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "upterm.fullname" . }}-letsencrypt
  labels:
    {{- include "upterm.labels" . | nindent 4 }}
spec:
 acme:
   # The ACME server URL
   {{ if .Values.websocket.stage_enabled }}
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   {{ else }}
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: {{ .Values.websocket.cert_manager_acme_email }}
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: {{ include "upterm.fullname" . }}-letsencrypt
   # Enable the HTTP-01 challenge provider
   solvers:
     - selector:
         dnsZones:
           {{- range $key, $val := .Values.websocket.dns_zones }}
           {{- $key }}: {{ $val }}
           {{- end }}

           #- flickify.com
       dns01:
         route53:
           region: {{ .Values.websocket.region }}
           hostedZoneID: {{ .Values.websocket.hosted_zone_id }}
{{- end }}
